### ISSUE TITLE
Sample initial data in the database

### ISSUE THREAD

**Issue by rpalival** [OmarAbdelmotaleb/Jobber#7]
Store some sample data in the database which can be used during testing connection to backend.

**Comment by amithvishnu** [comment]
1.Users:

Username: johndoe
Password: password123
Email: johndoe@example.com

2.Job Applications:

Company: Example Company
Position: Software Engineer
Location: New York, NY
Status: Applied
Date Applied: 2024-02-10
Notes: Phone interview scheduled for next week.

3.Reminders:

For Job Application #1:
Description: Follow up on application status
Due Date: 2024-02-25

4.Additional Notes:

For Job Application #1:
Description: Highlighted skills required: JavaScript, React, Node.js

This data represents a basic scenario where a user, John Doe, has applied to a job at "Example Company" for the position of Software Engineer in New York City. There's also a reminder set to follow up on the application and some additional notes regarding the skills required for the job.
